---
# tasks file for configure-haproxy
- name: install haproxy
  yum:
    name:
      - haproxy
      - python3-libsemanage
    state: latest
  notify:
  - restart haproxy
  - restart firewalld

- name: create /etc/haproxy
  file:
    path: /etc/haproxy
    state: directory

- name: create /etc/haproxy/haproxy.cfg
  template:
    src: etc/haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: allow http traffic
  firewalld:
    service: http
    permanent: yes
    zone: public
    state: enabled

- name: allow http traffic
  firewalld:
    service: http
    permanent: yes
    zone: internal
    state: enabled

- name: allow https traffic
  firewalld:
    service: https
    permanent: yes
    zone: public
    state: enabled

- name: allow https traffic
  firewalld:
    service: https
    permanent: yes
    zone: internal
    state: enabled

- name: allow traffic at port 443
  firewalld:
    port: 443/tcp
    permanent: yes
    zone: "{{ item }}"
    state: enabled
  with_items:
  - internal
  - public

- name: allow traffic at port 6443
  firewalld:
    port: 6443/tcp
    permanent: yes
    zone: "{{ item }}"
    state: enabled
  with_items:
  - internal
  - public

- name: allow traffic at port 22623
  firewalld:
    port: 22623/tcp
    permanent: yes
    zone: "{{ item }}"
    state: enabled
  with_items:
  - internal
  - public

- name: turn on haproxy_connect_any
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes

- name: restart haproxy
  service:
    name: haproxy.service
    state: restarted

- name: Restart firewalld.service
  service:
    name: firewalld.service
    state: restarted

